fix(TUP-24540)java.lang.NoSuchMethodError: (#4055)
org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540

Conflicts:
	main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java